version: "3"

services:
  strapi:
    container_name: strapiexample
    restart: unless-stopped
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      DATABASE_SSL: 'false'
    networks:
      - strapi-app-network
    volumes:
      - strapi:/srv/
    ports:
      - "1337:1337"
    depends_on:
      mysql: 
        condition: service_healthy

  n8n:
    container_name: n8n
    restart: unless-stopped
    image: n8nio/n8n
    environment:
      DB_TYPE: mysqldb
      DB_MYSQLDB_DATABASE: strapi
      DB_MYSQLDB_HOST: mysql
      DB_MYSQLDB_PORT: 3306
      DB_MYSQLDB_USER: strapi
      DB_MYSQLDB_PASSWORD: strapi
    ports:
      - "5678:5678"
    networks:
      - strapi-app-network
    links:
      - mysql
    volumes: 
      - n8n_data:/home/node/.n8n/
    depends_on:
      mysql: 
        condition: service_healthy
    

  mysql:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: strapi
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi
    networks:
      - strapi-app-network
    volumes:
      - mysqldb:/data/db
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

networks:
  strapi-app-network:
    driver: bridge

volumes:
  strapi:
  mysqldb:
  n8n_data:
